"use client"

import type { Metadata } from "next";

import "./globals.css";
import { Provider } from "react-redux";
import store from './Store';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
    <Provider store={store}>
      <body suppressHydrationWarning={true} >{children}</body>
      </Provider>
     
    </html>
  );
}
